apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: blueprints-workloads-oai
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /workloads/oai
    repo: https://github.com/nephio-project/catalog.git
  type: git
