apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nephio-webui
subjects:
- kind: ServiceAccount
  name: nephio-webui-sa
  namespace: nephio-webui
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
