apiVersion: v1
kind: Service
metadata:
  name: nephio-webui
  namespace: nephio-webui
  labels:
    app: nephio-webui
    app.kubernetes.io/name: nephio-webui
    app.kubernetes.io/instance: nephio-webui
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.18.0.201
spec:
  type: LoadBalancer
  selector:
    app: nephio-webui
  ports:
    - name: http
      port: 7007
      targetPort: http
