apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: vpc-cu-e1
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  topology: nephio
  routingTables:
  - name: vpc-cu-e1
    prefixes:
    - prefix: 172:4::/32
      labels:
        nephio.org/network-name: e1
    - prefix: 172.4.0.0/16
      labels:
        nephio.org/network-name: e1
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-cu-e1 
  bridgeDomains: 
  - name: vpc-cu-e1
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: vlan
