apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: vpc-cudu-f1
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  topology: nephio
  routingTables:
  - name: vpc-cudu-f1
    prefixes:
    - prefix: 172:5::/32
      labels:
        nephio.org/network-name: f1
    - prefix: 172.5.0.0/16
      labels:
        nephio.org/network-name: f1
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-cudu-f1 
  bridgeDomains: 
  - name: vpc-cudu-f1
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: vlan
