apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /resource-backend-controller-controller-role-binding
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
    app.kubernetes.io/version: tbd
  name: resource-backend-controller-controller-role-binding
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|resource-backend-controller-controller-role-binding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-backend-controller-controller-role
subjects:
- kind: ServiceAccount
  name: resource-backend-controller
  namespace: backend-system
