apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: backend-system/resource-backend-controller-leader-election-role-binding
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: resource-backend
    app.kubernetes.io/part-of: resource-backend
    app.kubernetes.io/version: tbd
  name: resource-backend-controller-leader-election-role-binding
  namespace: backend-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|backend-system|resource-backend-controller-leader-election-role-binding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: resource-backend-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: resource-backend-controller
  namespace: backend-system
