apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /network-config-controller-network-role
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: network-config
    app.kubernetes.io/part-of: network-config
    app.kubernetes.io/version: tbd
  name: network-config-controller-network-role
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|network-config-controller-network-role'
rules:
- apiGroups:
  - config.nephio.org
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - config.nephio.org
  resources:
  - networks/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
