apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-values
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: GenConfigMap
    name: gen-app-config
    fieldPath: params.hostname
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
