# Copyright 2022 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: ServiceAccount
apiVersion: v1
metadata: # kpt-merge: porch-system/porch-server
  name: porch-server
  namespace: porch-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|porch-system|porch-server'
    iam.gke.io/gcp-service-account: nephio-porch@example.iam.gserviceaccount.com # kpt-set: nephio-porch@${project-id}.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: porch-system/porch-server
  name: porch-server
  namespace: porch-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|porch-system|porch-server'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: porch-server
  template:
    metadata:
      labels:
        app: porch-server
    spec:
      serviceAccountName: porch-server
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: webhook-certs
          emptyDir: {}
        - name: api-server-certs
          emptyDir: {}
      containers:
        - name: porch-server
          # Update image to the image of your porch apiserver build.
          image: gcr.io/kpt-dev/porch-server:v0.0.31
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
              cpu: "3"
            limits:
              memory: 1Gi
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /etc/webhook/certs
              name: webhook-certs
            - name: api-server-certs
              mountPath: /tmp/certs
          env:
            # Uncomment to enable trace-reporting to jaeger
            #- name: OTEL
            #  value: otel://jaeger-oltp:4317
            - name: OTEL_SERVICE_NAME
              value: porch-server
            - name: CERT_STORAGE_DIR
              value: /etc/webhook/certs
          args:
            - --function-runner=function-runner:9445
            - --cache-directory=/cache
            - --cert-dir=/tmp/certs
            - --secure-port=4443
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: porch-system/api
  name: api
  namespace: porch-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|porch-system|api'
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 4443
      name: api
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: webhooks
  selector:
    app: porch-server
