apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
    cnrm.cloud.google.com/project-id: example # kpt-set: ${project-id}
  name: example # kpt-set: ${name}
  namespace: config-control
spec:
  description: Nephio Management Cluster
  location: example # kpt-set: ${location}
  initialNodeCount: 1
  workloadIdentityConfig:
    workloadPool: example.svc.id.goog # kpt-set: ${project-id}.svc.id.goog
  gatewayApiConfig:
    channel: CHANNEL_STANDARD
