apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: example-nodepool # kpt-set: ${name}-nodepool
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: example # kpt-set: ${project-id}
spec:
  location: example # kpt-set: ${location}
  autoscaling:
    totalMinNodeCount: 4
    totalMaxNodeCount: 10
  clusterRef:
    name: example # kpt-set: ${name}
  nodeConfig:
    machineType: e2-standard-4
    diskType: pd-standard
