apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: aws-nephio-md-0
  namespace: default
spec:
  clusterName: aws-nephio
  replicas: 1
  template:
    metadata:
      labels:
        cluster.x-k8s.io/deployment-name: aws-nephio-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: aws-nephio-md-0
      clusterName: aws-nephio
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachineTemplate
        name: aws-nephio-md-0
      version: v1.25.0
