apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-values
  annotations:
    config.kubernetes.io/local-config: "true"
source: |-
  load("krmfn.star", "krmfn")

  def generate_unique_string(length=8):
    # Simple method to generate a unique string without additional imports
    base_string = "abcdefghijklmnopqrstuvwxyz0123456789"
    unique_str = ""
    for i in range(length):
      unique_str += base_string[int(i * 3.14) % len(base_string)]
    return unique_str

  def set_values(resources):
    # Create a unique name using a custom generator
    new_name = generate_unique_string()

    # Update ConfigMap with new name
    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap"):
        if r["metadata"]["name"] == "aws-ebs-csi-driver-addon":
          r["metadata"]["name"] = new_name + "-aws-ebs-csi-driver-addon"
        elif r["metadata"]["name"] == "cloud-controller-manager-addon":
          r["metadata"]["name"] = new_name + "-cloud-controller-manager-addon"

    # Update ClusterResourceSet with new name
    for r in resources:
      if krmfn.match_gvk(r, "addons.cluster.x-k8s.io/v1beta1", "ClusterResourceSet"):
        if r["metadata"]["name"] == "crs-ccm":
          r["metadata"]["name"] = new_name + "-crs-ccm"
          # Update associated resources
          for resource in r["spec"]["resources"]:
            if resource["kind"] == "ConfigMap" and resource["name"] == "cloud-controller-manager-addon":
              resource["name"] = new_name + "-cloud-controller-manager-addon"
        elif r["metadata"]["name"] == "crs-csi":
          r["metadata"]["name"] = new_name + "-crs-csi"
          # Update associated resources
          for resource in r["spec"]["resources"]:
            if resource["kind"] == "ConfigMap" and resource["name"] == "aws-ebs-csi-driver-addon":
              resource["name"] = new_name + "-aws-ebs-csi-driver-addon"

  set_values(ctx.resource_list["items"])
