apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /nephio-controller-repository-role
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nephio
    app.kubernetes.io/part-of: nephio
    app.kubernetes.io/version: tbd
  name: nephio-controller-repository-role
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|nephio-controller-repository-role'
rules:
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.nephio.org
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - infra.nephio.org
  resources:
  - repositories/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
