apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /nephio-controller-approval-role
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nephio
    app.kubernetes.io/part-of: nephio
    app.kubernetes.io/version: tbd
  name: nephio-controller-approval-role
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|nephio-controller-approval-role'
rules:
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions
  - packagerevisions/status
  - packagerevisions/approval
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants
  - packagevariants/status
  verbs:
  - get
  - list
  - watch
